# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PROJECT_ID: ${{secrets.GKE_PROJECT}}
  GKE_CLUSTER: gks-demo-dev
  KGE_ZONE: us-central1-a
  DEPLOYMENT_NAME: gke-hello-app
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: set up deploy
    runs-on: ubuntu-latest

    permissions: 
      contents: 'read'
      id-token: 'write'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with: 
           credentials: '${{ secrets.GCP_CREDENTIALS }}'

      # Runs a single command using the runners shell
      - name: Set Up cloud SDK
        uses: 'google-github-actions/auth@v'


      # Runs a set of commands using the runners shell
        run: |-
          gcloud container cluster get credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
      - name: Deploy
        run: |-
          kubctl apply -f deployment.yml
          kubctl rollout status deployment/$DEPLOYMENT_NAME
          kubctl get servces -o wide
