name: ci

on:
  push:
    branches:
      - 'main'

  workflow_dispatch:

env:
  PROJECT_ID: ${{secrets.GKE_PROJECT}}
  GKE_CLUSTER: gke-demo-dev
  KGE_ZONE: us-central1-a
  DEPLOYMENT_NAME: gke-hello-app
jobs:
  docker:
    runs-on: ubuntu-latest
    
    permissions: 
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
            credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
   
      -
        name: Set up cloud sdk
        uses: google-github-actions/setup-gcloud@v0
        
      - run: |-
          gcloud container cluster get credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
      - name: Deploy
        run: |-
          kubectl apply -f deployl.yml
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get services -o wide
