name: ci

on:
  push:
    branches:
      - 'main'

  workflow_dispatch:

env:
  PROJECT_ID: ${{secrets.GKE_PROJECT}}
  GKE_CLUSTER: gke-demo-dev
  KGE_ZONE: us-central1-a
  DEPLOYMENT_NAME: gke-hello-app
jobs:
  docker:
    runs-on: ubuntu-latest
    
    permissions: 
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
            credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
   
      -
        name: Set up cloud sdk
        uses: google-github-actions/setup-gcloud@v0
        
        
      - 
        name: Checkout
        uses: actions/checkout@v3

      -
        name: Login to Docker Hub
        uses: docker/login-action@v1      
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
       # with:
          #credentials: "${{ secrets.GCP_CREDENTIALS }}"
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1  
      
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./hello-world-java/Dockerfile
          push: true
          tags: erapalo/hello-world-java:latest
          
      - run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone us-central1-a
      - name: Deploy
        run: |-
          kubectl apply -f deployment.yml
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get services -o wide
