apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - image: in28min/hello-world-rest-api:0.0.1.RELEASE
        name: test-app
        ports:
        - containerPort: 5000
          name: test-app 
---
apiVersion: v1
kind: Service
metadata:
  name: appservice
spec:
  type: LoadBalancer
  selector:
    app: test-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  
